### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by xFlacti0n** [Setraxis/TechGamesRP#4]
**Description:**

Login funktioniert nicht, man klicke auf Einloggen, jedoch ohne Erfolg 

**Current behaviour:**

---

**Expected behaviour:**

Weiterleitung zum Char erstellung oder co

**Steps to reproduce the problem:**

---

**Branch(es):**

---

**TGRP rev. hash/commit:** 

---

**Operating system:** WINDOWS

**Comment by Setraxis** [comment]
Wenn der Login bei dir nicht funktioniert, benutzt du eine falsche Verschlüsslung von deinem Passwort.

https://files.projekt-reallife.de/

Hier kannst du dein richtiges Passwort erstellen.

**Comment by Salumkas** [comment]
Bei mir kommt die ganze Zeit "[Auth] Es gab ein Fehler im login System"... Ih habe es aber so gemacht wie du es oben geschrieben hattest

**Comment by xFlacti0n** [comment]
Hab mir jetzt das Passwort per Hash generieren lassen, jedoch ohne Erfolg, passiert weiterhin nichts.

**Comment by neppelboom** [comment]
bekomme diese fehlermeldung jetzt ERROR - Garagen - SpawnAfterRestart: TypeError: Cannot read property 'getConnection' of undefined
