### ISSUE TITLE
Bug/Fehler

### ISSUE THREAD

**Issue by Ricoouu** [Setraxis/TechGamesRP#6]
Es gibt einen bug bzw fehler mit den charakteren/accounts  wen man nur 1 account mit einen charakter hat funktioniert alles aber wen man einen 2 charkter erstellt bekommt man stacktrace fehler wen man das Fahrzeug Menü öffnet wen man dann das game neu startet Spawnt man  in dem haus vom Login und der Charakter ist Standard auf einmal das gleiche passiert wen eine 2 Person Gewithlistet wird und  einen 2 Account erstellt und der nur 1 Charakter hat 

**Windows 10:**

**Comment by Setraxis** [comment]
Vorlage nicht eingehalten! Closed!
